---
suppress-bibliography: true
---

# Exercice markdown 

::: {.content-visible when-format="html" unless-format="revealjs"}

```{=html}
<iframe src="_slides/exercice-markdown.html"></iframe>
```
[Ouvrir dans mon navigateur](_slides/exercice-markdown.html){target="_blank"} 

::: 

## Markdown : langage de balisage léger 

Nous en avons parlé [ici](theorie-formats.qmd#markdown)

| Markdown             | Rendu graphique         | Balisage HTML                    |
|----------------------|-------------------------|----------------------------------|
| `Un texte _en italique_` | Un texte _en italique_ | `Un texte <em>en italique</em>` |
| `### Titre de niveau 3` | **Titre de niveau 3** | `<h3>Titre de niveau 3</h3>` |
| `Un [lien](https://www.unlien.org)` | Un [lien](https://www.unlien.org) | `Un <a href="https://www.unlien.org">lien</a>` |
| `Un texte **en gras**` | Un texte **en gras** | `Un texte <strong>en gras</strong>` |

## Tutoriel (à faire en classe) 

<https://www.arthurperret.fr/tutomd/>

## Rendu pour le 10 octobre 

- Texte : [pont_mirabeau.txt](img/pont_mirabeau.txt) ; 
- Image : [pont_mirabeau.png](img/pont_mirabeau.PNG) ; 
- Éditeur en ligne : [Dillinger](https://dillinger.io/) 

Faire un encodage en Markdown du poème :

- mettre le titre en niveau 1 ; 
- faire de chaque première ligne de strophe un titre de niveau 3 ; 
- mettre en italique le paratexte ; 
- mettre les noms propres en gras ; 
- sauver le document en ```.md``` ; 
- le déposer sur studium  / me l'envoyer par mail. 
