# Introduction 

::: {.content-visible when-format="html" unless-format="revealjs"}

```{=html}
<iframe src="../_slides/introduction.html"></iframe>
```

[Ouvrir dans mon navigateur](../_slides/introduction.html){target="_blank"} 

::: 


## Lecture du [plan de cours](plan-de-cours.qmd)

## Déroulement de l'atelier 

- Un peu de théorie 
- Beaucoup de pratique : on met les mains à la pâte, on teste des outils, on produit, on fabrique ! 

Vous n’êtes pas un groupe homogène donc vous n’irez pas toutes et tous à la même vitesse, pas d’inquiétude !

## Tour de table 

Quelques informations pour savoir qui vous êtes, quel est l’objectif de cet atelier et comment les séances vont être organisées.

5 questions :

- quel est votre nom ? 
- où étiez-vous l’année dernière ? 
- quel cursus suivez-vous cette année ? 
- pourquoi suivez-vous cet atelier ? 
- qu'est-ce qui vous vient instinctivement à l'esprit quand je vous dis format ?

## En ce qui me concerne {visibility="hidden"}

En ce qui me concerne, je m'appelle Mathilde Verstrate. Je suis doctorante au Département de littératures et de langues du monde à l'Université de Montréal, dans l'option humanités numériques. J'ai une formation en lettres classiques -- que j'ai suivie en Belgique, à l'Université Catholique de Louvain. Je suis passée du côté obscur de la force en rejoignant la Chaire de recherche du Canada sur les écritures numériques (dirigée par Marcello Vitali-Rosati). C'est à partir de ce moment là que j'ai commencé à m'intéresser et à me spécialiser dans les humanités numériques. J'étais donc grande débutante il y a peu, mais vous verrez, la courbe d'apprentissage n'est pas trop abrupte. C'est néanmoins la première fois que j'enseigne ce cours -- j'enseignais un cours de latin les années précédentes. 

## Me contacter 

N'hésitez pas à me contacter. Veillez à vous y prendre à l'avance si vous avez des questions conernant les rendus. 

[mathilde.verstraete@umontreal.ca](mailto:mathilde.verstraete@umontreal.ca)